language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'

sudo: true

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

env:
  - DB_NAME=raster_test PYTHONPATH=$PYTHONPATH:$PWD DJANGO_SETTINGS_MODULE=tests.testproj.settings

before_script:
  - psql -c 'create database raster_test' -U postgres
  - psql -c 'create extension postgis' -U postgres -d raster_test

install:
  - pip install https://github.com/geodesign/django/archive/geodesign_v9.tar.gz
  - pip install -e .
  - pip install psycopg2==2.7.3.2
  - pip install flake8==3.5.0
  - pip install isort==4.2.15
  - pip install flake8==3.3.0
  - pip install isort==4.2.2
  - pip install coverage==4.4
  - pip install coveralls
  - pip install mock

script: coverage run --include="raster/*" $(which django-admin.py) test

after_success: coveralls

notifications:
  email: false
